[workspace]
resolver = "2"
members = [
    "lotrc",
    "lotrc_rs",
    "lotrc_proc",
    "ffi", "lotrc_wrappers"]

[profile.release]
#strip = true
lto = true


[workspace.dependencies]
lotrc_proc = { path = "lotrc_proc" }
lotrc = { path = "lotrc" }
log = "0.4.21"
indexmap = "2.6.0"
zerocopy = "0.8.10"
anyhow = "1.0.86"
cbindgen = "0.29.2"
