[package]
name = "lotrc"
version = "0.1.0"
edition = "2021"

[features]
default = []
ffi = ["dep:safer-ffi"]

[dependencies]
lotrc_proc = { path = "../lotrc_proc" }
zerocopy = { workspace = true, features = ["derive", "alloc"] }
rend = { version = "0.5", features = ["zerocopy-0_8"] }
anyhow = { workspace = true }
log = { workspace = true }
indexmap = { workspace = true, features = ["serde", "rayon"] }
itertools = "0.13.0"
flate2 = { version = "1.0.35", features = ["zlib-ng"], default-features = false }
rayon = "1.10.0"
parking_lot = "0.12.3"
lazy_static = "1.5.0"
bcndecode = "0.2.0"
aligned-buffer = "0.2.0"
safer-ffi = { workspace = true, featuer = ["proc_macros"], optional = true }




